/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MunicipalRouteImport } from './routes/municipal'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as RequestRouteImport } from './routes/request'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as MunicipalLoginRouteImport } from './routes/municipal_.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalRoute = MunicipalRouteImport.update({
  id: '/municipal',
  path: '/municipal',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalLoginRoute = MunicipalLoginRouteImport.update({
  id: '/municipal_/login',
  path: '/municipal/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/municipal': typeof MunicipalRoute
  '/network': typeof NetworkRoute
  '/request': typeof RequestRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/municipal/login': typeof MunicipalLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/municipal': typeof MunicipalRoute
  '/network': typeof NetworkRoute
  '/request': typeof RequestRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/municipal/login': typeof MunicipalLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/municipal': typeof MunicipalRoute
  '/network': typeof NetworkRoute
  '/request': typeof RequestRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/municipal_/login': typeof MunicipalLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/municipal'
    | '/network'
    | '/request'
    | '/signup'
    | '/admin/login'
    | '/municipal/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/municipal'
    | '/network'
    | '/request'
    | '/signup'
    | '/admin/login'
    | '/municipal/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/municipal'
    | '/network'
    | '/request'
    | '/signup'
    | '/admin/login'
    | '/municipal_/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MunicipalRoute: typeof MunicipalRoute
  NetworkRoute: typeof NetworkRoute
  RequestRoute: typeof RequestRoute
  SignupRoute: typeof SignupRoute
  AdminLoginRoute: typeof AdminLoginRoute
  MunicipalLoginRoute: typeof MunicipalLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipal': {
      id: '/municipal'
      path: '/municipal'
      fullPath: '/municipal'
      preLoaderRoute: typeof MunicipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipal_/login': {
      id: '/municipal_/login'
      path: '/municipal/login'
      fullPath: '/municipal/login'
      preLoaderRoute: typeof MunicipalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MunicipalRoute: MunicipalRoute,
  NetworkRoute: NetworkRoute,
  RequestRoute: RequestRoute,
  SignupRoute: SignupRoute,
  AdminLoginRoute: AdminLoginRoute,
  MunicipalLoginRoute: MunicipalLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
